### PR TITLE
Add ListClients and DeleteClient operations

### LINKED ISSUE #22: Add support for ListClients and DeleteClient
Based on [this](https://github.com/parallaxsecond/parsec-client-rust/issues/66)

### PR DESCRIPTION
**Pull request by hug-dev**
Close #22

### CODE REVIEW

**Review by ionut-arm — APPROVED** [review]
Looks good, could you post a screenshot of the output? 😬

**Comment by ionut-arm** [comment]
I was also wondering - do you think we should put a prompt before deleting a client, like "are you sure you want to delete...?"

**Comment by hug-dev** [comment]
> Looks good, could you post a screenshot of the output? 😬

Yes sure, I will finish the implementation in Parsec and then post a screenshot of the test

> I was also wondering - do you think we should put a prompt before deleting a client, like "are you sure you want to delete...?"

hmm not sure about that, I would say admin should know what they are doing 😋

**Comment by hug-dev** [comment]
image

Something like this!

**Comment by hug-dev** [comment]
Had forgotten to add a new line

**Pull request merged**
